name: DFG SPP Computational Literary Studies
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
title: CLS
description: DFG Schwerpunktprogramm
array: []
collections:
  publications:
    output: true
  talks:
    output: false
